// Generated by scripts/brand.mjs from tokens.css. Do not edit by hand.
//
// For the handful of places that need a literal colour rather than a CSS
// variable: <meta> tags, and the terminal, which paints to a canvas and so
// cannot see the cascade at all.

export const BRAND = {
 mark: "#0961BB",
 ink: "#63A4FB",
 canvasDark: "#050607",
 canvasLight: "#F9FAFB",
 surfaceDark: "#090B0D",
 contentDark: "#F3F4F6"
} as const;
