/*
 * Derives every brand colour that cannot read a CSS variable from the one
 * place they are defined: tokens.css.
 *
 * The favicon, the mask-icon colour, the browser-chrome theme colour and the
 * terminal's palette are all files or strings that a stylesheet cannot reach.
 * Left to hand-maintenance they drift, and they did — the mark stayed lime
 * through a cyan brand and a pink one, so the tab looked like a different
 * product from the page.
 *
 *   pnpm brand          rewrite the generated files
 *   pnpm brand --check  fail if they are stale (runs as part of pnpm check)
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const TOKENS = join(root, 'src/lib/styles/tokens.css');
const FAVICON = join(root, 'static/favicon.svg');
const MODULE = join(root, 'src/lib/theme/brand.generated.ts');

const check = process.argv.includes('--check');

/** Pulls `--name: oklch(L C H)` out of the token file. */
function token(css, name) {
	const match = css.match(new RegExp(`--${name}:\\s*oklch\\(([\\d.]+)\\s+([\\d.]+)\\s+([\\d.]+)\\)`));
	if (!match) throw new Error(`brand: --${name} not found in tokens.css`);
	return [Number(match[1]), Number(match[2]), Number(match[3])];
}

/**
 * OKLCH to sRGB hex.
 *
 * Written out rather than pulled from a dependency: it is twenty lines of
 * matrix arithmetic, and a build script that rewrites committed files is not
 * somewhere to add a package for.
 */
function hex([L, C, h]) {
	const rad = (h * Math.PI) / 180;
	const a = C * Math.cos(rad);
	const b = C * Math.sin(rad);

	const l = (L + 0.3963377774 * a + 0.2158037573 * b) ** 3;
	const m = (L - 0.1055613458 * a - 0.0638541728 * b) ** 3;
	const s = (L - 0.0894841775 * a - 1.291485548 * b) ** 3;

	const channels = [
		4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s,
		-1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s,
		-0.0041960863 * l - 0.7034186147 * m + 1.707614701 * s
	];

	return (
		'#' +
		channels
			.map((v) => {
				// Linear light to sRGB, then clamped: deep chroma can land just
				// outside the gamut, and clipping is what a browser does too.
				const encoded = v <= 0.0031308 ? 12.92 * v : 1.055 * Math.pow(Math.max(v, 0), 1 / 2.4) - 0.055;
				const byte = Math.round(Math.min(1, Math.max(0, encoded)) * 255);
				return byte.toString(16).padStart(2, '0');
			})
			.join('')
			.toUpperCase()
	);
}

const css = readFileSync(TOKENS, 'utf8');

const brand = {
	// The mark's fill, and the colour Safari tints a pinned tab with.
	mark: hex(token(css, 'color-brand-700')),
	// The brand as ink on a dark surface — the terminal cursor uses this.
	ink: hex(token(css, 'color-brand-400')),
	canvasDark: hex(token(css, 'color-ink-1000')),
	canvasLight: hex(token(css, 'color-ink-50')),
	surfaceDark: hex(token(css, 'color-ink-950')),
	contentDark: hex(token(css, 'color-ink-100'))
};

const favicon = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" width="32" height="32">
	<!-- Generated by scripts/brand.mjs from tokens.css. Do not edit by hand. -->
	<rect width="32" height="32" rx="9" fill="${brand.mark}" />
	<g transform="translate(4 4)" stroke="#FFFFFF" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="none">
		<path d="M12 10.189V14" />
		<path d="M12 2v3" />
		<path d="M19 13V7a2 2 0 0 0-2-2H7a2 2 0 0 0-2 2v6" />
		<path d="M19.38 20A11.6 11.6 0 0 0 21 14l-8.188-3.639a2 2 0 0 0-1.624 0L3 14a11.6 11.6 0 0 0 2.81 7.76" />
		<path d="M2 21c.6.5 1.2 1 2.5 1 2.5 0 2.5-2 5-2 1.3 0 1.9.5 2.5 1s1.2 1 2.5 1c2.5 0 2.5-2 5-2 1.3 0 1.9.5 2.5 1" />
	</g>
</svg>
`;

const module = `// Generated by scripts/brand.mjs from tokens.css. Do not edit by hand.
//
// For the handful of places that need a literal colour rather than a CSS
// variable: <meta> tags, and the terminal, which paints to a canvas and so
// cannot see the cascade at all.

export const BRAND = ${JSON.stringify(brand, null, 1).replace(/"([a-zA-Z]+)":/g, '$1:')} as const;
`;

const files = [
	[FAVICON, favicon],
	[MODULE, module]
];

let stale = false;
for (const [path, content] of files) {
	let current = '';
	try {
		current = readFileSync(path, 'utf8');
	} catch {
		// Missing counts as stale.
	}

	if (current === content) continue;

	if (check) {
		console.error(`brand: ${path.replace(root + '/', '')} is out of date — run \`pnpm brand\``);
		stale = true;
	} else {
		writeFileSync(path, content);
		console.log(`brand: wrote ${path.replace(root + '/', '')}`);
	}
}

if (stale) process.exit(1);
if (!check) console.log(`brand: mark ${brand.mark}, ink ${brand.ink}`);
